apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwf1
  labels:
    app: testwf1
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727802436322
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwf1
  template:
    metadata:
      labels:
        app: testwf1
    spec:
      containers:
        - name: testwf1
          image: acrworkflow1727802436322.azurecr.io/image-workflow-1727802436322:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
