apiVersion: apps/v1
kind: Deployment
metadata:
  name: test003
  labels:
    app: test003
  namespace: namespace-workflow-1678727974140
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test003
  template:
    metadata:
      labels:
        app: test003
    spec:
      containers:
        - name: test003
          image: acrworkflow1678727974140.azurecr.io/image-workflow-1678727974140:latest
          ports:
            - containerPort: 80