apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0531
  labels:
    app: test0531
  namespace: namespace-workflow-1685558357420
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0531
  template:
    metadata:
      labels:
        app: test0531
    spec:
      containers:
        - name: test0531
          image: acrworkflow1685558357420.azurecr.io/image-workflow-1685558357420:latest
          ports:
            - containerPort: 80