apiVersion: v1
kind: Service
metadata:
  name: test003
  namespace: namespace-workflow-1678727974140
spec:
  type: LoadBalancer
  selector:
    app: test003
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80